services:
  postgres:
    image: postgres:16
    container_name: vaultcore-postgres
    restart: always
    environment:
      POSTGRES_DB: vaultcore_db
      POSTGRES_USER: vaultuser
      POSTGRES_PASSWORD: vaultpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: vaultcore-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vaultcore_db
      SPRING_DATASOURCE_USERNAME: vaultuser
      SPRING_DATASOURCE_PASSWORD: vaultpass

volumes:
  postgres_data: